blank_issues_enabled: true
contact_links:
    - name: Report a Security Vulnerability
      url: https://github.com/lenorix/datadis-php-client/security/policy
      about: Please report security issues privately, not in a public issue
